apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image-to-video-frontend
  annotations:
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/image-to-video-frontend
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://image-to-video-backend-xxxxx-an.a.run.app/api/v1"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-key
              key: key
        - name: KLING_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: kling-access
              key: key
        - name: KLING_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: kling-secret
              key: key
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"